title: Sp-tester
description: A free testing tool created for self improvement
template:
  repo: sp-tester-template
  name: sp-tester
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
